export const metadata = {
  title: 'Luxury Skin',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className='bg-gradient-to-r from-black via-red-500 to-gray-50'>{children}</body>
    </html>
  )
}
